[project]
name = "money-making-machine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyarrow==16.0.0",
    "streamlit==1.37.1",
]
